### PR TITLE
[Chore] Bump morley &c

### PR DESCRIPTION
**Pull request by lierdakil**
## Description

- Bump morley
- Update CI to run on Lima
- Simplify CI dependencies to pull everything from morley-infra.

## Related issue(s)

Part of TM-667

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [ ] I checked whether I should update the docs and did so if necessary:
    - [README](https://github.com/tqtezos/stablecoin/tree/master/README.md)
    - Haddock
  - [ ] I updated [changelog](https://github.com/tqtezos/stablecoin/tree/master/ChangeLog.md) unless I am sure my changes are
        not essential.

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](https://github.com/tqtezos/stablecoin/tree/master/docs/code-style.md).

#### ✓ Release Checklist

- [ ] I updated the [Gas / Transaction costs](https://github.com/tqtezos/stablecoin/tree/master/README.md#gas--transaction-costs) table in the README.
- [ ] I updated the version number in `package.yaml`.
- [ ] I updated the [changelog](https://github.com/tqtezos/stablecoin/tree/master/ChangeLog.md) and moved everything
      under the "Unreleased" section to a new section for this release version.
- [ ] (After merging) I created a new entry in the [releases](https://github.com/tqtezos/stablecoin/releases) page,
      with a summary of all user-facing changes.
    * I made sure a tag was created using the format `vX.Y.Z`
    * I attached the following artifacts from [buildkite](https://buildkite.com/serokell/stablecoin)
      * `stablecoin-client`
      * `stablecoin.fa1.2.tz`
      * `stablecoin.tz`

### CODE REVIEW

**Comment by lierdakil** [comment]
I'm not convinced if bumping Morley version used for optimization is a good idea or not, needs additional investigation.

**Comment by lierdakil** [comment]
Okay, no appreciable difference between morley 16.2 and 19.0 in terms of optimization, the only difference is in some formatting, which arguably doesn't matter. Might as well update.

**Review by pasqu4le — APPROVED** [review]
:+1:

**Comment by lierdakil** [comment]
Okay, I'm confused about changelogs. There are two, one in the root, one in `haskell` sub-directory. The latter is empty, and everything is dumped into the former. Perhaps I could remove the redundant one in `haskell` while at it?

**Comment by pasqu4le** [comment]
Indeed, the one in the `haskell` directory seems to have never been used and was probably forgotten...
 
@lierdakil please go ahead and remove that file entirely

**Pull request merged**
