### PR TITLE
Update repository structure, morley, Makefiles

### LINKED ISSUE #20: Setup CI properly
# Clarification and motivation

Our CI currently has several issues:
1. Uses `stack` to build Haskell code. We normally use `haskell.nix` instead, it works better.
2. Does not run `hlint`.
3. It does not compile LIGO code to produce Michelson.

Our tentative plan is to do #8 and #13, then do this issue. As result of #8 and #13, workflow should be the following: run `ligo` to produce `stablecoin.tz`, then run tests written in Haskell that require `stablecoin.tz`.

# Acceptance criteria

CI uses `haskell.nix` instead of `stack`, runs `hlint`, compiles LIGO code.

### PR DESCRIPTION
**Pull request by gromakovsky**
## Description

See commits, but in short:
1. Some cleanup.
2. Updated `morley` and resolver for Haskell code.
3. Update Makefiles so that now `make test*` commands will compile `stablecoin.tz` (only if it needs recompilation) and run Haskell tests (that now depend on `stablecoin.tz`).

## Related issue(s)

Resolves #20

#### Related changes (conditional)

- Tests
  - [xx] If I added new functionality, I added tests covering it.
  - [x] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Comment by gromakovsky** [comment]
@balsoft can you please port your PR for #20 here?

**Comment by balsoft** [comment]
@gromakovsky Sure. What's the timeframe? I'll try to do this today or tomorrow.

**Comment by gromakovsky** [comment]
@balsoft today or tomorrow sounds fine. AFAIU you have already made `ligo` available on CI in #26, so I expect it to take not much time. If it's the case, I'd like it to be done today. So I treat it as a small task, but I realize there can be some complications. If they appear, well, we can wait.

**Comment by balsoft** [comment]
```
  fatal: reference is not a tree: 84a465af9e15b57ba6ed3ed3a4d35a638551ca56
  Unable to checkout 84a465af9e15b57ba6ed3ed3a4d35a638551ca56 from https://gitlab.com/morley-framework/morley.git.
```

**Pull request merged**
