### PR TITLE
[#60] Optimize `mint` entrypoint

### LINKED ISSUE #60: Validate sender once in `mint`
# Clarification and motivation

Apparently `mint_tokens` validates sender in a loop.
```
  ( (nil : list (operation))
  , List.fold
      ( function
          ( const accumulator : storage
          ; const mint_param  : mint_param
          ) : storage is case accumulator.minting_allowances[senderAddress] of
            None -> (failwith ("NOT_MINTER") : storage)
          | Some (current_allowance) ->
              mint_tokens (accumulator, mint_param, current_allowance)
          end
      , parameters
      , store
      )
  )
```

But it's a bit inefficient because sender stays constant. I believe we can do it more efficiently by extracting sender's minting allowance once and updating only allowance in the loop, not the whole storage.
Also we do `authorize_minter` at the beginning (after `ensure_not_paused`). I suppose we can return `nat` from `authorize_minter` and not check sender anymore.

# Acceptance criteria

`mint` validates sender only once if that's more efficient (I believe it is, but we should check).

### PR DESCRIPTION
**Pull request by awkure**
Problem: We have some unnecessary checks for sender validation that
only increase gas costs and thought the very parameter needs to be
refactored.

Solution: Refactor `mint` entrypoint.

## Related issue(s)

Resolves #60 

#### Related changes (conditional)

- Tests
  - [X] If I added new functionality, I added tests covering it.
  - [X] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

- Documentation
  - [X] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

#### Stylistic guide (mandatory)

- [X] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [X] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Comment by gromakovsky** [comment]
So did you check how it affects contract size and gas costs?

**Comment by awkure** [comment]
Actually contract size is bigger 🤔

**Comment by gromakovsky** [comment]
Okay, then can you revert to the previous version, but still return current minting allowance from `authorize_minter` so that we don't do `accumulator.minting_allowances[senderAddress]` twice? Hopefully at least this change will be beneficial.

**Comment by gromakovsky** [comment]
I was told that even with this new attempt with a smaller and simpler "optimization" the contract size still gets bigger than before the "optimization". I am not sure why, but I suppose we shouldn't spend more time on that, looks like we won't save much gas even if we try hard.

**Pull request closed without merging**
